apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatares-devops-pj1-frontend
spec:
  selector:
    matchLabels:
      app: avatares-devops-pj1-frontend
  template:
    metadata:
      labels:
        app: avatares-devops-pj1-frontend
    spec:
      containers:
        - name: avatares-devops-pj1-frontend
          image: brxvn/avatares-devops-pj1-frontend
          ports:
            - containerPort: 5173
              name: http
              protocol: TCP
          env:
            - name: VITE_HOST
              valueFrom:
                configMapKeyRef:
                  name: avatares-devops-pj1-frontend
                  key: VITE_HOST
            - name: VITE_PORT
              valueFrom:
                configMapKeyRef:
                  name: avatares-devops-pj1-frontend
                  key: VITE_PORT