apiVersion: v1
kind: Service
metadata:
  name: avatares-devops-pj1-frontend-svc
  labels:
    app: avatares-devops-pj1-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5173
  selector:
    app: avatares-devops-pj1-frontend
  type: ClusterIP