apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatares-devops-pj1-backend
spec:
  selector:
    matchLabels:
      app: avatares-devops-pj1-backend
  template:
    metadata:
      labels:
        app: avatares-devops-pj1-backend
    spec:
      containers:
        - name: avatares-devops-pj1-backend
          image: brxvn/avatares-devops-pj1-backend
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP