apiVersion: v1
kind: Service
metadata:
  name: avatares-devops-pj1-backend-svc
  labels:
    app: avatares-devops-pj1-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: avatares-devops-pj1-backend
  type: ClusterIP