apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avatares-devops-pj1-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bootcamp-prj-1
    server: https://kubernetes.default.svc
  project:  bry-devops-bootcamp
  source:
    path: project-1/avatares-devops-backend
    repoURL: https://github.com/whoisbryan/GitOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
